# Generated by Django 5.2 on 2025-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите почту получателя", max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите полное имя получателя",
                        max_length=100,
                        null=True,
                        verbose_name="Полное имя получателя",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Введите комментарий о получателе", null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["id", "email"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme",
                    models.CharField(help_text="Введите тему письма", max_length=100, verbose_name="Тема письма"),
                ),
                (
                    "body_massage",
                    models.TextField(help_text="Введите текст сообщения", verbose_name="Текст сообщений"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["id", "theme"],
            },
        ),
    ]
