# Generated by Django 5.2 on 2025-04-15 06:49

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_sending",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 4, 15, 11, 49, 9, 42968),
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "stop_sending",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 4, 15, 11, 49, 9, 42968),
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Завершена"), ("created", "Создана"), ("running", "Запущена")],
                        default="created",
                        max_length=9,
                        verbose_name="Статус автоматической рассылки",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="mailing", to="sending_messages.client", verbose_name="Получатели"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing",
                        to="sending_messages.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["id"],
                "permissions": [("can_cancel_mailing", "Can cancel mailing")],
            },
        ),
    ]
