# Generated by Django 5.2 on 2025-04-15 07:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0003_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 15, 12, 36, 18, 603297), verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="stop_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 15, 12, 36, 18, 603297),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.CreateModel(
            name="MailingStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempted_at", models.DateTimeField(verbose_name="Дата и время попытки отправки")),
                (
                    "status",
                    models.BooleanField(default=False, help_text="Статус рассылки", verbose_name="Статус рассылки"),
                ),
                (
                    "mail_server_response",
                    models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="sending_messages.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["id"],
            },
        ),
    ]
