# Generated by Django 5.2 on 2025-04-15 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0004_alter_mailing_start_sending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 15, 12, 37, 28, 118839), verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="stop_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 15, 12, 37, 28, 118839),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
    ]
