# Generated by Django 5.2 on 2025-04-15 09:25

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0005_alter_mailing_start_sending_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="body_massage",
            new_name="body_message",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 15, 14, 25, 38, 539436), verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="stop_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 15, 14, 25, 38, 539436),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
