# Generated by Django 5.2 on 2025-05-22 13:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0006_rename_body_massage_message_body_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 22, 18, 34, 41, 254357), verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="stop_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 22, 18, 34, 41, 254357),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
    ]
