# Generated by Django 5.2 on 2025-05-22 15:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0007_alter_mailing_start_sending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 22, 20, 41, 41, 829258), verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="stop_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 22, 20, 41, 41, 829258),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingstatus",
            name="attempted_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата и время попытки отправки"),
        ),
    ]
