# Generated by Django 5.2 on 2025-06-04 05:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0009_alter_mailing_start_sending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 4, 10, 14, 33, 178927), verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="stop_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 4, 10, 14, 33, 178927),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
    ]
