# Generated by Django 5.2 on 2025-06-22 21:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0010_alter_mailing_start_sending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 23, 2, 44, 26, 71760), verbose_name="Дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="stop_sending",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 23, 2, 44, 26, 71760),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
    ]
